Added my name to devotees.
ashiishme/open-source-enthusiasts pull request #86
Opened 2020-10-03 02:04 UTC by Kapersky1337

2020-10-03 02:29 UTC, ashiishme commented
@Kapersky1337  Hey, please update the details based on the new contributing instruction. You need to add more details in your markdown file.

2020-10-03 03:30 UTC, ashiishme requested changes
Based on the above comment, once you update this PR it will be merged.

2020-10-04 19:51 UTC, Kapersky1337 commented
Hello, I've updated it as requested.

2020-10-08 13:40 UTC, ashiishme approved these changes

2020-10-08 13:40 UTC, merged